### PR TITLE
Add rationale and update document locations

### PR DESCRIPTION
**Pull request by zkoch**
Added a rationale document as an addition to original explainer. Moved these into docs/.

### CODE REVIEW

**Comment by zkoch** [comment]
I have no idea with the IPR check is failing

**Comment by zkoch** [comment]
IPR problem is magically fixed!

**Comment by adrianba** [comment]
I just fixed it. :)

**Comment by zkoch** [comment]
@adrianba used magic to fix the ipr problem!

**Comment by adrianba** [comment]
Merged as 37c6e06223ee7e226e2692caba74508a07cd1d44

**Comment by ianbjacobs** [comment]
@zkoch,

It's called Magic ® !

**Comment by msporny** [comment]
@zkoch, I think you meant @adrianba _is_ magic®?

**Pull request closed without merging**
