### PR TITLE
Minor spec changes based on implementation experience and feedback

### PR DESCRIPTION
**Pull request by adrianba**
Most significant change is to use strings for amount value based on more discussion. Also moved some validation steps in show() earlier.

### CODE REVIEW

**Comment by zkoch** [comment]
So now we have "details", "options", and "data" and it's not super clear from their names what is what. I wonder if we should re-think these. At the very least, perhaps, data should be "methodData".

**Comment by adrianba** [comment]
> So now we have "details", "options", and "data" and it's not super clear from their names what is what. I wonder if we should re-think these. At the very least, perhaps, data should be "methodData".

Well, those names are just in an example and as argument names to a method, which explains them. They need never appear in anyone's code. I don't mind what we call them but they don't seem important.

**Comment by zkoch** [comment]
I think it just helps with clarity about what is expected to go in to that particular dictionary. That said, agreed that it's not super important. Merging.

**Comment by adrianba** [comment]
> I think it just helps with clarity about what is expected to go in to that particular dictionary.

Feel free to propose a change - this PR just makes the two places in the spec match. The example didn't match the method definition before.

**Comment by adrianhopebailie** [comment]
Does it make sense to combine the `supportedMethods` and `data` parameters?

i.e. The set of keys in the `data` object is basically the same set of values in the `supportedMethods` array.

A supported method with no additional data would simply be included in the `data` object with the method identifier as the key and an empty object as the value.

**Pull request merged**
