### PR TITLE
Added initial spec drafts and architecture overview.

### PR DESCRIPTION
**Pull request by adrianba**
I've created initial drafts based on the explainer document to give us something to start with. There are lots of open issues called out, linking to the appropriate GitHub issue where possible. I've tried to make sure that all relevant GitHub issues in this repo are linked from the appropriate section.

### CODE REVIEW

**Comment by msporny** [comment]
Hey @adrianba @zkoch - I was planning on doing a spec review this weekend on paymentrequest, but don't have anything to link to yet. Any chance you guys could get this merged before tomorrow? Also, could you put the master branch on gh_pages so that we could view the spec from the Web via github.io?

**Comment by adrianba** [comment]
I don't currently have write access to the repo.

In the meantime, you can view the documents from my fork here:
* [Architecture](http://github.adrianba.net/paymentrequest/specs/architecture.html)
* [Payment Method Identifiers](http://github.adrianba.net/paymentrequest/specs/method-identifiers.html)
* [Payment Request API](http://github.adrianba.net/paymentrequest/specs/paymentrequest.html)

**Comment by msporny** [comment]
Great, thanks @adrianba - I'll just ref your spec branch when I do the review (if it isn't done before I do the review), no need for the merge to do that.

**Comment by zkoch** [comment]
Sorry for delay. Was out yesterday.

**Pull request merged**
